
export const keys = {
    GET_ALLL_TASK_TYPES:  "GET_ALLL_TASK_TYPES",
    ADD_TASK_TYPES:  "ADD_TASK_TYPES",
    DELETE_TASK_TYPES:  "DELETE_TASK_TYPES",
    GET_BY_ID_TASK_TYPES:  "GET_BY_ID_TASK_TYPES",
    UPDATE_TASK_TYPES:  "UPDATE_TASK_TYPES",
}