export const keys = {
  // Keys for Task Types
  GET_ALLL_TASK_TYPES: "GET_ALLL_TASK_TYPES",
  ADD_TASK_TYPES: "ADD_TASK_TYPES",
  DELETE_TASK_TYPES: "DELETE_TASK_TYPES",
  GET_BY_ID_TASK_TYPES: "GET_BY_ID_TASK_TYPES",
  UPDATE_TASK_TYPES: "UPDATE_TASK_TYPES",
  // Keys for Priorities
  GET_ALLL_PRIORITIES: "GET_ALLL_PRIORITIES",
  ADD_PRIORITIES: "ADD_PRIORITIES",
  DELETE_PRIORITIES: "DELETE_PRIORITIES",
  GET_BY_ID_PRIORITIES: "GET_BY_ID_PRIORITIES",
  UPDATE_PRIORITIES: "UPDATE_PRIORITIES",
  // Keys for Status
  GET_ALLL_STATUS: "GET_ALLL_STATUS",
  ADD_STATUS: "ADD_STATUS",
  DELETE_STATUS: "DELETE_STATUS",
  GET_BY_ID_STATUS: "GET_BY_ID_STATUS",
  UPDATE_STATUS: "UPDATE_STATUS",
  // Keys for Project
  GET_ALLL_PROJECTS: "GET_ALLL_PROJECTS",
  ADD_PROJECT: "ADD_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  GET_BY_ID_PROJECT: "GET_BY_ID_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",

  // Keys for Project
  GET_ALLL_BUCKETS: "GET_ALLL_BUCKETS",
  ADD_BUCKET: "ADD_BUCKET",
  DELETE_BUCKET: "DELETE_BUCKET",
  GET_BY_ID_BUCKET: "GET_BY_ID_BUCKET",
  UPDATE_BUCKET: "UPDATE_BUCKET",
};
